# This is a basic workflow to help you get started with Actions

name: App Deploy To Github Page

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build app
      env:
        REACT_APP_BASE_URL: ${ {secrets.REACT_APP_BASE_URL }}
      run: npm run build

    - name: Deploy react app to github pages
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
